// Generated by delombok at Thu Oct 10 16:50:19 CDT 2019
/*
 * Copyright 2002-2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.pivotal.cla.data;

import java.io.Serializable;
import java.util.Set;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Transient;
import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
public class User implements Serializable {
	@Id
	@Column(name = "github_login")
	private String gitHubLogin;
	private String name;
	private String accessToken;
	@JsonProperty("avatar_url")
	private String avatarUrl;
	@ElementCollection
	@Column(name = "email")
	@CollectionTable(name = "user_email", joinColumns = @JoinColumn(name = "github_login"))
	private Set<String> emails;
	@Transient
	private boolean admin;
	@Transient
	private boolean claAuthor;
	@Transient
	private boolean adminAccessRequested;
	private static final long serialVersionUID = 7285385090438382841L;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public User() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getGitHubLogin() {
		return this.gitHubLogin;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getAccessToken() {
		return this.accessToken;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getAvatarUrl() {
		return this.avatarUrl;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Set<String> getEmails() {
		return this.emails;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isAdmin() {
		return this.admin;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isClaAuthor() {
		return this.claAuthor;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isAdminAccessRequested() {
		return this.adminAccessRequested;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setGitHubLogin(final String gitHubLogin) {
		this.gitHubLogin = gitHubLogin;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setName(final String name) {
		this.name = name;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAccessToken(final String accessToken) {
		this.accessToken = accessToken;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAvatarUrl(final String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setEmails(final Set<String> emails) {
		this.emails = emails;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAdmin(final boolean admin) {
		this.admin = admin;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setClaAuthor(final boolean claAuthor) {
		this.claAuthor = claAuthor;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAdminAccessRequested(final boolean adminAccessRequested) {
		this.adminAccessRequested = adminAccessRequested;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "User(gitHubLogin=" + this.getGitHubLogin() + ", name=" + this.getName() + ", accessToken=" + this.getAccessToken() + ", avatarUrl=" + this.getAvatarUrl() + ", emails=" + this.getEmails() + ", admin=" + this.isAdmin() + ", claAuthor=" + this.isClaAuthor() + ", adminAccessRequested=" + this.isAdminAccessRequested() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof User)) return false;
		final User other = (User) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$gitHubLogin = this.getGitHubLogin();
		final java.lang.Object other$gitHubLogin = other.getGitHubLogin();
		if (this$gitHubLogin == null ? other$gitHubLogin != null : !this$gitHubLogin.equals(other$gitHubLogin)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$accessToken = this.getAccessToken();
		final java.lang.Object other$accessToken = other.getAccessToken();
		if (this$accessToken == null ? other$accessToken != null : !this$accessToken.equals(other$accessToken)) return false;
		final java.lang.Object this$avatarUrl = this.getAvatarUrl();
		final java.lang.Object other$avatarUrl = other.getAvatarUrl();
		if (this$avatarUrl == null ? other$avatarUrl != null : !this$avatarUrl.equals(other$avatarUrl)) return false;
		final java.lang.Object this$emails = this.getEmails();
		final java.lang.Object other$emails = other.getEmails();
		if (this$emails == null ? other$emails != null : !this$emails.equals(other$emails)) return false;
		if (this.isClaAuthor() != other.isClaAuthor()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof User;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $gitHubLogin = this.getGitHubLogin();
		result = result * PRIME + ($gitHubLogin == null ? 43 : $gitHubLogin.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $accessToken = this.getAccessToken();
		result = result * PRIME + ($accessToken == null ? 43 : $accessToken.hashCode());
		final java.lang.Object $avatarUrl = this.getAvatarUrl();
		result = result * PRIME + ($avatarUrl == null ? 43 : $avatarUrl.hashCode());
		final java.lang.Object $emails = this.getEmails();
		result = result * PRIME + ($emails == null ? 43 : $emails.hashCode());
		result = result * PRIME + (this.isClaAuthor() ? 79 : 97);
		return result;
	}
}
