This tool is intended to allow managing GitHub Contributor License Agreements.

= Setup

Below are the steps that are necessary to set this project up.

== Register a new OAuth application with GitHub

This application uses https://developer.github.com/v3/oauth/[OAuth to access GitHub's APIs].
The first step is to https://github.com/settings/applications/new[Register a new OAuth application] with GitHub.

Example values for the form might be:

* *Application Name* - Pivotal CLA
* *Homepage URL* - https://pivotal.io
* *Application description* - Allows managing Contributor License Agreements for contributions to Pivotal sponsored projects
* *Authorization callback URL* - This needs to point back to your application's OAuth endpoint.
For development it might be http://localhost:8080/login/oauth2/github
If you are needing to test receiving GitHub events, you will probably want to setup https://ngrok.com/#download[ngrok].
If you are using ngrok, the URL would look something like https://123456.ngrok.io/login/oauth2/github

After clicking *Register application* you should make the application aware of the *Client ID* and the *Client Secret*.

Create a new file named *application-local.properties*

.src/main/resources/application-local.properties
[source]
----
# Replace values from registered application at https://github.com/settings/developers
# See the README for additional detail
security.oauth2.main.clientId=Value from Client ID
security.oauth2.main.clientSecret=Value from Client Secret
----

In order to ensure that stored access tokens for managing the github hooks are not accidentally down graded in scope, we need to Register another OAuth application for the admin portion of the application.
Repeat the above steps with the following values:

Example values for the form might be:

* *Application Name* - Pivotal CLA Admin
* *Homepage URL* - https://pivotal.io
* *Application description* - Allows managing Contributor License Agreements for contributions to Pivotal sponsored projects
* *Authorization callback URL* - This needs to point back to your application's OAuth endpoint.
For development it might be http://localhost:8080/login/oauth2/github
If you are needing to test receiving GitHub events, you will probably want to setup https://ngrok.com/#download[ngrok].
If you are using ngrok, the URL would look something like https://123456.ngrok.io/

After clicking *Register application* you should make the application aware of the *Client ID* and the *Client Secret*.

Modify *application-local.properties*

.src/main/resources/application-local.properties
[source]
----
# Replace values from registered application at https://github.com/settings/developers
# See the README for additional detail
security.oauth2.admin.clientId=Value from Client ID
security.oauth2.admin.clientSecret=Value from Client Secret
security.oauth2.main.clientId=Value from Client ID
security.oauth2.main.clientSecret=Value from Client Secret
----

== Register a personal access token

* Generate a [New personal access token](https://github.com/settings/tokens/new) that contains only `public_repo` scope.
This will be used for adding comments to pull requests that require the contributor to sign the CLA.
* Copy the personal access token and place it in application-local.properties

Modify *application-local.properties*

.src/main/resources/application-local.properties
[source]
----
# Replace values from registered application at https://github.com/settings/developers
# See the README for additional detail
security.oauth2.admin.clientId=Value from Client ID
security.oauth2.admin.clientSecret=Value from Client Secret
security.oauth2.main.clientId=Value from Client ID
security.oauth2.main.clientSecret=Value from Client Secret
security.oauth2.pivotal-cla.token=A Personal Access Token with public_repo scope
----

== Setup ngrok

If you are needing to test receiving GitHub events, you will probably want to setup https://ngrok.com/#download[ngrok].
If there is no need to test reciving the GitHub events from GitHub, then you can skip this step.

== Open the Application

You can open the application at a context root of "/".
If you are running, the default URL is at http://localhost:8080/
