// Generated by delombok at Thu Oct 10 16:50:19 CDT 2019
/*
 * Copyright 2002-2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.pivotal.cla.mvc.util;

import java.net.URLEncoder;
import javax.servlet.http.HttpServletRequest;
import org.springframework.http.server.ServletServerHttpRequest;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.util.UriComponentsBuilder;

/**
 * @author Rob Winch
 */
public class UrlBuilder {
	private final HttpServletRequest request;
	private String path;
	private MultiValueMap<String, String> params = new LinkedMultiValueMap<>();

	private UrlBuilder(HttpServletRequest request) {
		this.request = request;
	}

	public String callbackUrl() {
		return path("/login/oauth2/github").build();
	}

	public UrlBuilder param(String name, String value) {
		this.params.add(name, value);
		return this;
	}

	public UrlBuilder path(String path) {
		this.path = path;
		return this;
	}

	private static String createSignUrl(HttpServletRequest request, String claName, String repositoryId, int pullRequestId) {
		try {
			String urlEncodedClaName = URLEncoder.encode(claName, "UTF-8");
			UrlBuilder url =  //
			//
			//
			//
			UrlBuilder.fromRequest(request).path("/sign/" + urlEncodedClaName).param("repositoryId", repositoryId).param("pullRequestId", String.valueOf(pullRequestId));
			return url.build();
		} catch (final java.lang.Throwable $ex) {
			throw lombok.Lombok.sneakyThrow($ex);
		}
	}

	public static String createSyncUrl(HttpServletRequest request, String claName, String repositoryId, int pullRequestId) {
		try {
			String urlEncodedClaName = URLEncoder.encode(claName, "UTF-8");
			UrlBuilder url =  //
			//
			//
			//
			UrlBuilder.fromRequest(request).path("/sync/" + urlEncodedClaName).param("repositoryId", repositoryId).param("pullRequestId", String.valueOf(pullRequestId));
			return url.build();
		} catch (final java.lang.Throwable $ex) {
			throw lombok.Lombok.sneakyThrow($ex);
		}
	}

	public static String createAboutUrl(HttpServletRequest request) {
		try {
			UrlBuilder url =  //
			//
			UrlBuilder.fromRequest(request).path("/about");//
			return url.build();
		} catch (final java.lang.Throwable $ex) {
			throw lombok.Lombok.sneakyThrow($ex);
		}
	}

	public String build() {
		String url =  //
		//
		//
		//
		//
		UriComponentsBuilder.fromHttpRequest(new ServletServerHttpRequest(request)).replacePath(path).replaceQueryParams(params).build().toUriString(); //
		this.path = null;
		this.params.clear();
		if (url.contains("ngrok.io")) {
			url = url.replaceFirst(":80", "");
			url = url.replaceFirst("http:", "https:");
		}
		return url;
	}

	public static UrlBuilder fromRequest(HttpServletRequest request) {
		return new UrlBuilder(request);
	}

	public static String pullRequestHookCallbackPath(String claName) {
		try {
			String urlEncodedClaName = URLEncoder.encode(claName, "UTF-8");
			return String.format("%s/%s", "/github/hooks/pull_request", urlEncodedClaName);
		} catch (final java.lang.Throwable $ex) {
			throw lombok.Lombok.sneakyThrow($ex);
		}
	}


	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public static class StringBuilder {
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		private HttpServletRequest request;
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		private String claName;
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		private String repositoryId;
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		private int pullRequestId;

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		StringBuilder() {
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public StringBuilder request(final HttpServletRequest request) {
			this.request = request;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public StringBuilder claName(final String claName) {
			this.claName = claName;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public StringBuilder repositoryId(final String repositoryId) {
			this.repositoryId = repositoryId;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public StringBuilder pullRequestId(final int pullRequestId) {
			this.pullRequestId = pullRequestId;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public String build() {
			return UrlBuilder.createSignUrl(request, claName, repositoryId, pullRequestId);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public java.lang.String toString() {
			return "UrlBuilder.StringBuilder(request=" + this.request + ", claName=" + this.claName + ", repositoryId=" + this.repositoryId + ", pullRequestId=" + this.pullRequestId + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public static StringBuilder signUrl() {
		return new StringBuilder();
	}
}
