// Generated by delombok at Thu Oct 10 16:50:19 CDT 2019
package io.pivotal.cla.egit.github.core;

import java.io.Serializable;
import org.eclipse.egit.github.core.Repository;

public class WithPermissionsRepository extends Repository {
	private Permission permissions;


	public static class Permission implements Serializable {
		private boolean admin;
		private boolean pull;
		private boolean push;
		private static final long serialVersionUID = 8935105985140617959L;

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public Permission() {
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public boolean isAdmin() {
			return this.admin;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public boolean isPull() {
			return this.pull;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public boolean isPush() {
			return this.push;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public void setAdmin(final boolean admin) {
			this.admin = admin;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public void setPull(final boolean pull) {
			this.pull = pull;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public void setPush(final boolean push) {
			this.push = push;
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public boolean equals(final java.lang.Object o) {
			if (o == this) return true;
			if (!(o instanceof WithPermissionsRepository.Permission)) return false;
			final Permission other = (Permission) o;
			if (!other.canEqual((java.lang.Object) this)) return false;
			if (this.isAdmin() != other.isAdmin()) return false;
			if (this.isPull() != other.isPull()) return false;
			if (this.isPush() != other.isPush()) return false;
			return true;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		protected boolean canEqual(final java.lang.Object other) {
			return other instanceof WithPermissionsRepository.Permission;
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public int hashCode() {
			final int PRIME = 59;
			int result = 1;
			result = result * PRIME + (this.isAdmin() ? 79 : 97);
			result = result * PRIME + (this.isPull() ? 79 : 97);
			result = result * PRIME + (this.isPush() ? 79 : 97);
			return result;
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public java.lang.String toString() {
			return "WithPermissionsRepository.Permission(admin=" + this.isAdmin() + ", pull=" + this.isPull() + ", push=" + this.isPush() + ")";
		}
	}

	private static final long serialVersionUID = 7009511040709634862L;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public WithPermissionsRepository() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Permission getPermissions() {
		return this.permissions;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setPermissions(final Permission permissions) {
		this.permissions = permissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "WithPermissionsRepository(permissions=" + this.getPermissions() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof WithPermissionsRepository)) return false;
		final WithPermissionsRepository other = (WithPermissionsRepository) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$permissions = this.getPermissions();
		final java.lang.Object other$permissions = other.getPermissions();
		if (this$permissions == null ? other$permissions != null : !this$permissions.equals(other$permissions)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof WithPermissionsRepository;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $permissions = this.getPermissions();
		result = result * PRIME + ($permissions == null ? 43 : $permissions.hashCode());
		return result;
	}
}
