insert into contributor_license_agreement (id,name,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1, 'pivotal',true,NOW(),'### Pivotal Software, Inc.

### Individual Contributor License Agreement

In order to clarify the intellectual property license granted with Contributions (as defined below) from any person or entity, Pivotal Software, Inc. (“Pivotal”) must have a Contributor License Agreement (“ICLA” or “Agreement”) on file that has been signed by each Contributor (as defined below), indicating agreement to the license terms below.  This license is for your protection as a Contributor as well as for the protection of Pivotal and its users; it does not change your rights to use your own Contributions for any other purpose.


To agree to this ICLA, please read this document carefully, complete and submit.  Be sure to keep a copy for your records.

In consideration of the opportunity to participate in the community of contributors to Pivotal projects, You accept and agree to the following terms and conditions for Your present and future Contributions submitted to Pivotal.  Except for the license granted herein to Pivotal and recipients of software distributed by Pivotal, You reserve all right, title, and interest in and to Your Contributions.

1) <u>Definitions</u>.  “You” (or “Your”) shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement to Pivotal.  For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor.  For the purposes of this definition, “control” means (i) the power, direct or indirect, to cause the direction or management or such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
“Contribution” shall mean any original work of authorship, including any modifications, or additions to an existing work, that is intentionally submitted by You to Pivotal for inclusion in, or documentation of, any of the projects owned or managed by Pivotal (the “Project”).  For the purposes of this definition, “submitted” means any form of electronic, verbal, or written communication sent to Pivotal or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Pivotal for the purpose of discussing and improving the Project, but excluding communication that is conspicuously marked or otherwise designated in writing by You as “Not a Contribution.”


2.  <u>Grant of Copyright License</u>.  Subject to the terms and conditions of this Agreement, You hereby grant to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.


3.  <u>Grant of Patent License</u>.  Subject to the terms and conditions of this Agreement, You hereby grant to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section), patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Project, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Project to which such Contribution(s) was submitted.  If any entity institutes patent litigation against You or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that your Contribution, or the Project to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Project shall terminate as of the date such litigation is filed.


4.  You represent that you are legally entitled to grant the above license.  If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to Pivotal, or that your employer has executed a separate Corporate CLA with Pivotal.


5.  You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others).  You represent that Your Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.


6.  You are not expected to provide support for Your Contributions, except to the extent You desire to provide support.  You may provide support for free, for a fee, or not at all.  Unless required by applicable law or agreed to in writing, You provide Your Contributions on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.


7.  Should You wish to submit work that is not Your original creation, You may submit it to Pivotal separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as “Submitted on behalf of a third-party: [named here]”.


8.  You agree to notify Pivotal of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.


9.  This Agreement is governed by the laws of the State of California, without regard to its choice of law provisions, and by the laws of the United States.  This Agreement sets forth the entire understanding and agreement between the parties, and supersedes any previous communications, representations or agreements, whether oral or written, regarding the subject matter herein.
','<div id="out"><h3>Pivotal Software, Inc.</h3>
<h3>Individual Contributor License Agreement</h3>
<p>In order to clarify the intellectual property license granted with Contributions (as defined below) from any person or entity, Pivotal Software, Inc. (“Pivotal”) must have a Contributor License Agreement (“ICLA” or “Agreement”) on file that has been signed by each Contributor (as defined below), indicating agreement to the license terms below.  This license is for your protection as a Contributor as well as for the protection of Pivotal and its users; it does not change your rights to use your own Contributions for any other purpose.</p>
<p>To agree to this ICLA, please read this document carefully, complete and submit.  Be sure to keep a copy for your records.</p>
<p>In consideration of the opportunity to participate in the community of contributors to Pivotal projects, You accept and agree to the following terms and conditions for Your present and future Contributions submitted to Pivotal.  Except for the license granted herein to Pivotal and recipients of software distributed by Pivotal, You reserve all right, title, and interest in and to Your Contributions.</p>
<ol>
<li><u>Definitions</u>.  “You” (or “Your”) shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement to Pivotal.  For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor.  For the purposes of this definition, “control” means (i) the power, direct or indirect, to cause the direction or management or such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
“Contribution” shall mean any original work of authorship, including any modifications, or additions to an existing work, that is intentionally submitted by You to Pivotal for inclusion in, or documentation of, any of the projects owned or managed by Pivotal (the “Project”).  For the purposes of this definition, “submitted” means any form of electronic, verbal, or written communication sent to Pivotal or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Pivotal for the purpose of discussing and improving the Project, but excluding communication that is conspicuously marked or otherwise designated in writing by You as “Not a Contribution.”</li>
</ol>
<ol start="2">
<li><u>Grant of Copyright License</u>.  Subject to the terms and conditions of this Agreement, You hereby grant to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.</li>
</ol>
<ol start="3">
<li><u>Grant of Patent License</u>.  Subject to the terms and conditions of this Agreement, You hereby grant to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section), patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Project, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Project to which such Contribution(s) was submitted.  If any entity institutes patent litigation against You or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that your Contribution, or the Project to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Project shall terminate as of the date such litigation is filed.</li>
</ol>
<ol start="4">
<li>You represent that you are legally entitled to grant the above license.  If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to Pivotal, or that your employer has executed a separate Corporate CLA with Pivotal.</li>
</ol>
<ol start="5">
<li>You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others).  You represent that Your Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.</li>
</ol>
<ol start="6">
<li>You are not expected to provide support for Your Contributions, except to the extent You desire to provide support.  You may provide support for free, for a fee, or not at all.  Unless required by applicable law or agreed to in writing, You provide Your Contributions on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.</li>
</ol>
<ol start="7">
<li>Should You wish to submit work that is not Your original creation, You may submit it to Pivotal separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as “Submitted on behalf of a third-party: [named here]”.</li>
</ol>
<ol start="8">
<li>You agree to notify Pivotal of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.</li>
</ol>
<ol start="9">
<li>This Agreement is governed by the laws of the State of California, without regard to its choice of law provisions, and by the laws of the United States.  This Agreement sets forth the entire understanding and agreement between the parties, and supersedes any previous communications, representations or agreements, whether oral or written, regarding the subject matter herein.</li>
</ol>
</div>','### Pivotal Software, Inc.

#### Corporate Contributor License Agreement

In order to clarify the intellectual property license granted with Contributions (as defined below) from any person or entity, Pivotal Software, Inc. (“Pivotal”) must have a Contributor License Agreement ("CLA" or “Agreement”) on file that has been signed by each Contributor (as defined below), indicating agreement to the license terms below. This license is for the protection of Contributors as well as the protection of Pivotal and its users; it does not change the Contributor’s rights to use Contributions for any other purpose. This version of the CLA allows an entity (the "Company") to submit Contributions to Pivotal, to authorize Contributions submitted by its designated employees to Pivotal, and to grant Pivotal copyright and patent licenses to such Contributions.

To agree to this Corporate CLA, please read this document carefully, complete and submit.  Be sure to keep a copy for your records.

In consideration of the opportunity to participate in the community of contributors to Pivotal projects, Company accepts and agrees to the following terms and conditions for Company’s present and future Contributions submitted to Pivotal. Except for the license granted herein to Pivotal and recipients of software distributed by Pivotal, Company reserves all right, title, and interest in and to Company’s Contributions.

1. <u>Definitions</u>. “Company" shall mean the legal entity that is making this Agreement with Pivotal. All other entities that control, are controlled by, or are under common control with Company are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.

		"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by Company to Pivotal for inclusion in, or documentation of, any of the projects owned or managed by Pivotal (the "Project"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Pivotal or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Pivotal for the purpose of discussing and improving the Project, but excluding communication that is conspicuously marked or otherwise designated in writing by Company as "Not a Contribution."


2.  <u>Grant of Copyright License</u>. Subject to the terms and conditions of this Agreement, Company hereby grants to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Company’s Contributions and such derivative works.


3.  <u>Grant of Patent License</u>. Subject to the terms and conditions of this Agreement, Company hereby grants to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no- charge, royalty-free, irrevocable (except as stated in this section), patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Project, where such license applies only to those patent claims licensable by Company that are necessarily infringed by Company’s Contribution(s) alone or by combination of Company’s Contribution(s) with the Project to which such Contribution(s) was submitted. If any entity institutes patent litigation against Company or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that Company’s Contribution, or the Project to which Company has contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Project shall terminate as of the date such litigation is filed.


4.  Company represents that Company is legally entitled to grant the above license. If Company’s employee(s) has rights to intellectual property that that is included in Company’s Contributions, Company represents that Company has received permission to make Contributions on behalf of such employee(s), that such employee(s) has waived such rights for such Contributions to Pivotal, or that such employee(s) has executed a separate CLA with Pivotal.


5.  Contributions submitted by any member of Company’s authorized GitHub organization shall be considered Company’s Contributions and Company will be responsible for maintaining its authorized GitHub organization membership. Company represents that each of Company’s Contributions is Company’s or its employees’ original creation (see section 7 for submissions on behalf of others). Company represents that Company’s Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which Company is aware and which is associated with any part of Company’s Contributions.


6.  Company is not expected to provide support for Company’s Contributions, except to the extent Company desires to provide support. Company may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, Company provides Company’s Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.


7.  Should Company wish to submit work that is not Company’s original creation, Company may submit it to Pivotal separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which Company is aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".


8.  Company agrees to notify Pivotal a cla@pivotal.io of any facts or circumstances of which it becomes aware that would make these representations inaccurate in any respect.


9.  This Agreement is governed by the laws of the State of California, without regard to its choice of law provisions, and by the laws of the United States. This Agreement sets forth the entire understanding and agreement between the parties, and supersedes any previous communications, representations or agreements, whether oral or written, regarding the subject matter herein.


10.  By clicking on the “I have read and agree to the entire Corporate Contributor License Agreement”, the person executing this CLA on behalf of Company represents that she/he has the authority to sign on behalf of, and bind Company to, the terms and conditions of this CLA.
', '<div id="out"><h3>Pivotal Software, Inc.</h3>
<h4>Corporate Contributor License Agreement</h4>
<p>In order to clarify the intellectual property license granted with Contributions (as defined below) from any person or entity, Pivotal Software, Inc. (“Pivotal”) must have a Contributor License Agreement ("CLA" or “Agreement”) on file that has been signed by each Contributor (as defined below), indicating agreement to the license terms below. This license is for the protection of Contributors as well as the protection of Pivotal and its users; it does not change the Contributor’s rights to use Contributions for any other purpose. This version of the CLA allows an entity (the "Company") to submit Contributions to Pivotal, to authorize Contributions submitted by its designated employees to Pivotal, and to grant Pivotal copyright and patent licenses to such Contributions.</p>
<p>To agree to this Corporate CLA, please read this document carefully, complete and submit.  Be sure to keep a copy for your records.</p>
<p>In consideration of the opportunity to participate in the community of contributors to Pivotal projects, Company accepts and agrees to the following terms and conditions for Company’s present and future Contributions submitted to Pivotal. Except for the license granted herein to Pivotal and recipients of software distributed by Pivotal, Company reserves all right, title, and interest in and to Company’s Contributions.</p>
<ol>
<li>
<p><u>Definitions</u>. “Company" shall mean the legal entity that is making this Agreement with Pivotal. All other entities that control, are controlled by, or are under common control with Company are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.</p>
<p>"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by Company to Pivotal for inclusion in, or documentation of, any of the projects owned or managed by Pivotal (the "Project"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Pivotal or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Pivotal for the purpose of discussing and improving the Project, but excluding communication that is conspicuously marked or otherwise designated in writing by Company as "Not a Contribution."</p>
</li>
</ol>
<ol start="2">
<li><u>Grant of Copyright License</u>. Subject to the terms and conditions of this Agreement, Company hereby grants to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Company’s Contributions and such derivative works.</li>
</ol>
<ol start="3">
<li><u>Grant of Patent License</u>. Subject to the terms and conditions of this Agreement, Company hereby grants to Pivotal and to recipients of software distributed by Pivotal a perpetual, worldwide, non-exclusive, no- charge, royalty-free, irrevocable (except as stated in this section), patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Project, where such license applies only to those patent claims licensable by Company that are necessarily infringed by Company’s Contribution(s) alone or by combination of Company’s Contribution(s) with the Project to which such Contribution(s) was submitted. If any entity institutes patent litigation against Company or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that Company’s Contribution, or the Project to which Company has contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Project shall terminate as of the date such litigation is filed.</li>
</ol>
<ol start="4">
<li>Company represents that Company is legally entitled to grant the above license. If Company’s employee(s) has rights to intellectual property that that is included in Company’s Contributions, Company represents that Company has received permission to make Contributions on behalf of such employee(s), that such employee(s) has waived such rights for such Contributions to Pivotal, or that such employee(s) has executed a separate CLA with Pivotal.</li>
</ol>
<ol start="5">
<li>Contributions submitted by any member of Company’s authorized GitHub organization shall be considered Company’s Contributions and Company will be responsible for maintaining its authorized GitHub organization membership. Company represents that each of Company’s Contributions is Company’s or its employees’ original creation (see section 7 for submissions on behalf of others). Company represents that Company’s Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which Company is aware and which is associated with any part of Company’s Contributions.</li>
</ol>
<ol start="6">
<li>Company is not expected to provide support for Company’s Contributions, except to the extent Company desires to provide support. Company may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, Company provides Company’s Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.</li>
</ol>
<ol start="7">
<li>Should Company wish to submit work that is not Company’s original creation, Company may submit it to Pivotal separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which Company is aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".</li>
</ol>
<ol start="8">
<li>Company agrees to notify Pivotal a <a href="mailto:cla@pivotal.io">cla@pivotal.io</a> of any facts or circumstances of which it becomes aware that would make these representations inaccurate in any respect.</li>
</ol>
<ol start="9">
<li>This Agreement is governed by the laws of the State of California, without regard to its choice of law provisions, and by the laws of the United States. This Agreement sets forth the entire understanding and agreement between the parties, and supersedes any previous communications, representations or agreements, whether oral or written, regarding the subject matter herein.</li>
</ol>
<ol start="10">
<li>By clicking on the “I have read and agree to the entire Corporate Contributor License Agreement”, the person executing this CLA on behalf of Company represents that she/he has the authority to sign on behalf of, and bind Company to, the terms and conditions of this CLA.</li>
</ol>
</div>');

insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'','N/A',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'dependency management gradle plugin','ICLA FINAL 101414',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'donovan muller','ICLA FINAL 101414',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'eclipse','ICLA FINAL 010912',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'eclipse','ICLA FINAL 090414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'eclipse','ICLA FINAL 101414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'grails','1',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'grails','1.1',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'grails','ICLA FINAL 010912',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'grails','ICLA FINAL 072310',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'grails','ICLA FINAL 090414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'grails','N/A',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'hyperic','1',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'hyperic','ICLA FINAL 010912',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'hyperic','ICLA FINAL 072310',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'hyperic','N/A',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'rabbitmq','05132013 - RabbitMQ',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'rabbitmq','10062010 - RabbitMQ',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'rabbitmq','N/A',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'reactor','ICLA FINAL 090414',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'reactor','ICLA FINAL 101414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'scripted','ICLA FINAL 010912',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'scripted','ICLA FINAL 090414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','1',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','1.1',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','ICLA FINAL 010912',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','ICLA FINAL 072310',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','ICLA FINAL 090414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','ICLA FINAL 101414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','N/A',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'spring','Pivotal ICLA 101414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'vert.x','ICLA FINAL 010912',true, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'vert.x','ICLA FINAL 072310',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');
insert into contributor_license_agreement (superseding_cla_id,name,description,primary_cla,created,individual_markdown,individual_html,corporate_markdown,corporate_html) values (1,'vert.x','ICLA FINAL 090414',false, NOW(), 'Agreement on file.','Agreement on file.','Agreement on file.','Agreement on file.');

